#!/bin/bash


set -e

if [ -z ${WDY_XBUILD_ROOT} ]; then
	echo "WDY_XBUILD_ROOT not set!"
	exit 1
fi

DIR=$(readlink -f $(dirname $0))


${WDY_XBUILD_ROOT}/bin/cmake-android-build ${DIR} --asm-by-cc -Dld-version-script=OFF -DBUILD_SHARED_LIBS=YES

${WDY_XBUILD_ROOT}/bin/prepare_libraries.sh


